name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install g++
        run: |
          sudo apt-get update
          sudo apt-get install g++

      - name: Set up Environment
        run: echo "/home/runner/work/_temp/-1661514204/cmake-3.17.1-Linux-x86_64/bin/" >> $GITHUB_PATH

      - name: Set up CMake
        uses: lukka/get-cmake@v2

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: SimpleFactory
          path: build/SimpleFactory

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: build/Testing/Temporary

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
